[package]
name = "gobrowse-web"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
gloo-net = { version = "0.6.0", features = ["http", "json"] }
js-sys = "0.3.104"
leptos.workspace = true
serde.workspace = true
serde_json.workspace = true
url.workspace = true
wasm-bindgen-futures = "0.4.50"
wasm-bindgen = "0.2.127"
web-sys = { version = "0.3.77", features = ["HtmlElement", "HtmlInputElement", "HtmlPreElement", "Window", "Location", "Storage"] }

[lints]
workspace = true
